""""CONSTANTS."""


LOW_ENERGY: int = 1
MODERATE_ENERGY: int = 2
HIGH_ENERGY: int = 3

ALONE: int = 0,
SURROUNDED: int = 1,
SMALL_GROUP: int = 2,
LARGE_GROUP: int = 3

THIRTY_MIN: int = 30
SIXTY_MIN: int = 60
NINETY_MIN: int = 90